# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd data/cosmos/
    npm install
  displayName: 'npm install'

- script: |
    cd data/cosmos/
    node seedMetadata.js
  displayName: 'Seed Metadata'
