# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Fetch
    jobs:
      - job: Fetch_New_Data
        steps:
          - script: |
              cd data/
              npm install
            displayName: 'npm install'
          - script: |
              cd data/intake/
              node getCases.js
            displayName: 'Fetch Case Data'
          - script: |
              cd data/intake/
              node getGeneticTree.js
            displayName: 'Fetch Phylogenetic Tree from Nextstrain'
          - publish: $(System.DefaultWorkingDirectory)/data/artifacts
            artifact: data
            displayName: 'Publish Data Artifact'
  - stage: Seed
    condition: succeeded()
    jobs:
      - job: Metadata
        steps:
          - script: |
              cd data/
              npm install
            displayName: 'npm install'
          - script: |
              cd data/cosmos/
              node seedMetadata.js
            displayName: 'Seed Metadata'
      - job: CaseReports
        dependsOn: Metadata
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: current
              artifact: data
              targetPath: $(System.DefaultWorkingDirectory)/data/artifacts
            displayName: 'Download New Data Artifact'
          - script: |
              cd data/
              npm install
            displayName: 'npm install'
          - script: |
              cd data/cosmos/
              node seedCaseReports.js
            displayName: 'Seed Case Reports'
      - job: GeneticData
        dependsOn: Metadata
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: current
              artifact: data
              targetPath: $(System.DefaultWorkingDirectory)/data/artifacts
            displayName: 'Download New Data Artifact'
          - script: |
              cd data/
              npm install
            displayName: 'npm install'
          - script: |
              cd data/cosmos/
              node seedGenetics.js
            displayName: 'Seed Phylogenetic Tree'