# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Fetch_New_Data
    steps:
      - script: |
          cd data/
          npm install
        displayName: 'npm install'
      - script: |
          cd data/intake/
          node getCases.js
        displayName: 'Fetch Case Data'
      - script: |
          cd data/intake/
          node getGeneticTree.js
        displayName: 'Fetch Phylogenetic Tree from Nextstrain'
  - job: Seed_Graph
    dependsOn: Fetch_New_Data
    condition: succeededOrFailed()
    steps:
      - script: |
          cd data/cosmos/
          node seedMetadata.js
        displayName: 'Seed Metadata'
      - script: |
          cd data/cosmos/
          node seedCaseReports.js
        displayName: 'Seed Case Reports'
      - script: |
          cd data/cosmos/
          node seedGenetics.js
        displayName: 'Seed Phylogenetic Tree'
      - script: |
          cd data/cosmos/
          node linkGeneticMetadata.js
        displayName: 'Link Genetic Metadata'
